import { useEffect } from "react";
import Navigation from "@/components/Navigation";

const LegalNotices = () => {
  useEffect(() => {
    // SEO meta tags
    document.title = "Legal Notices | MyAuditionAI";
    
    // Meta description
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute("content", "Legal notices and disclaimers for MyAuditionAI - Important information about liability, intellectual property, and service limitations.");
    } else {
      const meta = document.createElement("meta");
      meta.name = "description";
      meta.content = "Legal notices and disclaimers for MyAuditionAI - Important information about liability, intellectual property, and service limitations.";
      document.head.appendChild(meta);
    }

    // Canonical URL
    const canonicalLink = document.querySelector('link[rel="canonical"]');
    if (canonicalLink) {
      canonicalLink.setAttribute("href", window.location.origin + "/legal");
    } else {
      const link = document.createElement("link");
      link.rel = "canonical";
      link.href = window.location.origin + "/legal";
      document.head.appendChild(link);
    }
  }, []);

  return (
    <main className="min-h-screen bg-background">
      <Navigation />
      <div className="pt-20 pb-12 px-4">
        <div className="max-w-4xl mx-auto">
          <header className="mb-8">
            <h1 className="text-4xl font-bold text-foreground mb-4">Legal Notices</h1>
            <p className="text-muted-foreground text-lg">
              Important legal information and disclaimers
            </p>
          </header>

          <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8">
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">Disclaimer of Liability</h2>
              <p className="text-muted-foreground">
                MyAuditionAI provides acting tools, AI-powered analysis, and coaching resources for informational and educational purposes only. We do not guarantee employment, casting outcomes, or any specific results from using our services. All feedback, reports, or evaluations generated by the AI or provided by coaches are suggestions only and should not be considered definitive or professional guarantees.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">Intellectual Property</h2>
              <p className="text-muted-foreground">
                All content, trademarks, logos, software, training materials, and features displayed on this website are the exclusive property of MyAuditionAI, unless otherwise stated. You may not reproduce, distribute, or modify any material without express written permission.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">Third-Party Content</h2>
              <p className="text-muted-foreground">
                The website may include links to third-party vendors, payment processors, or partner services. MyAuditionAI is not responsible for the content, accuracy, or practices of these external sites.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">Limitation of Liability</h2>
              <p className="text-muted-foreground">
                To the maximum extent permitted by law, MyAuditionAI is not liable for any direct, indirect, incidental, or consequential damages arising from use of the platform, including but not limited to loss of data, loss of business opportunities, or service interruptions.
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
};

export default LegalNotices;